### PR TITLE
Update Commons IO from 1.4 to 2.2

### PR DESCRIPTION
**Pull request by cordje**
This PR brings zt-zip to the latest version of Commons IO that supports Java 1.5. The Commons IO 2.2 classes were truncated to match the previous truncations of Commons IO 1.4 in PR https://github.com/zeroturnaround/zt-zip/pull/55

Thankfully, each new Commons IO version from 1.4 to 2.2 is binary, source, and semantic compatible, so it wasn't a complicated job, and presents very low risk to the project.

The least straightforward part was that zt-zip's FileUtils class had at some point been modified to add some zt-zip specific methods, e.g. getTempFileFor(File). To simplify this, I've separated two classes: 

- FileUtilsV2_2.java (purely from Commons IO)
- FileUtils (extends the former class, and adds zt-zip's specific methods). 

This will ease future upgrades to Commons IO, and has not required any changes to the codebase that depends on the FileUtils class.

There are numerous bug fixes and enhancements from 4 upgrades, (in areas that zt-zip does use):
- http://commons.apache.org/proper/commons-io/upgradeto2_2.html
- http://commons.apache.org/proper/commons-io/upgradeto2_1.html
- http://commons.apache.org/proper/commons-io/upgradeto2_0_1.html
- http://commons.apache.org/proper/commons-io/upgradeto2_0.html

The Commons IO updates (v2.3 and 2.4) that zt-zip can't make use of due to the Java 1.5 constraint, are not important, since the bug fixes cited in the changelogs are for features not used by zt-zip.

### CODE REVIEW

**Comment by cordje** [comment]
Also included is a wider set of test cases for FilePermissionsTest, since previously there was only one test (for executable), and it failed on Windows (which uses ACL's rather than file permissions) because, to cite the javadocs:

> "the underlying file system does not implement an execute permission, then the operation will fail"

(I didn't create a new branch because it wasn't worth the hassle, sorry for the large PR!)

**Comment by toomasr** [comment]
It is looking good but what is the motivation for the Commons upgrade?

**Comment by reinra** [comment]
Seems good. I'll also run the unit tests on different OSes to confirm it's ok (I verified it failed on Windows before this PR).

**Comment by reinra** [comment]
Tests are now green also on Windows. Thank you for the contribution!

**Comment by cordje** [comment]
No problem. Any chance of a new build on maven central soon so I can use it in a project?

@toomasr - the bug fixes do indeed apply to this project. A few examples:

* [IO-207] FileUtils - fix race condition in forceMkdir() method
  * Is used by:
    * org.zeroturnaround.zip.Zips.UnpackingCallback.process(InputStream, ZipEntry)
    * org.zeroturnaround.zip.ZipUtil.BackslashUnpacker.process(InputStream, ZipEntry)
    * org.zeroturnaround.zip.ZipUtil.Unpacker.process(InputStream, ZipEntry)
*  [IO-190] FileUtils - fix copyDirectory not preserving lastmodified date on sub-directories
  * Is used by:
    * org.zeroturnaround.zip.Zips.handleInPlaceActions(File)
* [IO-266] FileUtils.copyFile() throws IOException when copying large files to a shared directory (on Windows) & [IO-264] FileUtils.moveFile() JavaDoc should specify FileExistsException thrown
  * Is used by:
    * org.zeroturnaround.zip.ZipUtil.explode(File)
    * org.zeroturnaround.zip.Zips.handleInPlaceActions(File)
    * org.zeroturnaround.zip.ZipUtil.operateInPlace(File, InPlaceAction)
    * org.zeroturnaround.zip.ZipUtil.repack(File, int)
    * org.zeroturnaround.zip.ZipUtil.unexplode(File, int)
* [IO-168] FileUtils - fix Symbolic links followed when deleting directory
   * Is used by:
     * org.zeroturnaround.zip.ZipUtil.unexplode(File, int)
     * org.zeroturnaround.zip.Zips.handleInPlaceActions(File)
     * org.zeroturnaround.zip.ZipUtil.doUnpackEntry(ZipFile, String, File)
     * lots more (+10 calls)
* [IO-298] Various methods of class 'org.apache.commons.io.FileUtils' incorrectly suppress 'java.io.IOException'
* [IO-223] IOUtils.copy() documentation corrections
* [IO-191] Improvements from static analysis
* +more

**Comment by toomasr** [comment]
Ok, thank you for the detailed explanation. We'll bump the version today.

**Comment by toomasr** [comment]
Release done, will take some time to propagate to central.

**Pull request merged**
