### PR TITLE
Added createEmpty(File) method in ZipUtil

### PR DESCRIPTION
**Pull request by domisum**
Added a method for creating an empty zip archive.

### CODE REVIEW

**Comment by toomasr** [comment]
I've implemented the empty file differently now. Can you take a look if you still are experiencing the issue? I used the bytes from https://en.wikipedia.org/wiki/Zip_(file_format)#Limits to create the empty file.

**Comment by tschmidt01** [comment]
> I've implemented the empty file differently now. Can you take a look if you still are experiencing the issue? I used the bytes from https://en.wikipedia.org/wiki/Zip_(file_format)#Limits to create the empty file.

Any plans on releasing these changes to central?

**Comment by toomasr** [comment]
I'll whip up a changelog update and get it done. I'll ping here once done.

**Comment by toomasr** [comment]
And it is done. The version 1.14 is out. Might need to wait for Maven central to actually propagate this through its internal but the release process was a success. I don't see the file at https://repo1.maven.org/maven2/org/zeroturnaround/zt-zip/1.14 yet but usually it gets there in 30-60min time.

**Pull request merged**
